In [1]:
# Import necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Load the Iris dataset
dataset = pd.read_csv('./data/iris.csv')

In [3]:
# Separate features and target
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
# Split the dataset into an 80-20 training-test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [5]:
# Apply feature scaling on the training and test sets
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, :] = sc.fit_transform(X_train[:, :])
X_test[:, :] = sc.transform(X_test[:, :])

In [6]:
# Print the scaled training and test sets
print(X_train)

[[-0.16295021  1.68825931 -1.1416515  -1.14819173]
 [ 0.30847807 -0.52806284  0.15601426  0.19643199]
 [-0.75223557  1.02336267 -1.254492   -1.28265411]
 [ 1.25133465  0.1368338   0.77663701  1.54105571]
 [-1.34152093  0.35846602 -1.3673325  -1.28265411]
 [-0.98794971 -2.30112057 -0.12608699 -0.20695513]
 [-0.51652143  1.4666271  -1.254492   -1.28265411]
 [ 1.13347757 -0.52806284  0.60737626  0.33089436]
 [ 2.07633415 -0.08479841  1.62294077  1.27213096]
 [ 0.54419222  0.58009823  0.55095601  0.5998191 ]
 [ 1.0156205  -1.19295949  1.17157876  0.86874385]
 [ 0.07276393 -0.08479841  0.26885476  0.46535673]
 [-0.87009264  1.68825931 -1.028811   -1.01372936]
 [-0.28080728 -0.08479841  0.43811551  0.46535673]
 [ 1.13347757 -0.08479841  1.00231801  1.27213096]
 [-0.16295021 -0.08479841  0.26885476  0.06196961]
 [-0.04509314 -0.97132728  0.15601426  0.06196961]
 [ 1.36919172  0.35846602  0.55095601  0.33089436]
 [-1.22366386  0.1368338  -1.19807175 -1.28265411]
 [ 2.42990536  1.68825931  1.51

In [7]:
print(X_test)

[[-0.98794971  0.80173045 -1.254492   -1.28265411]
 [-0.39866435 -1.19295949  0.15601426  0.19643199]
 [ 0.42633515 -0.30643063  0.32527501  0.19643199]
 [-0.98794971  0.80173045 -1.19807175 -1.01372936]
 [ 0.77990636  0.35846602  0.77663701  1.13766859]
 [ 0.66204929 -0.52806284  1.05873826  1.27213096]
 [-0.75223557 -0.74969506  0.09959401  0.33089436]
 [-1.459378    1.24499488 -1.53659325 -1.28265411]
 [ 1.60490586 -0.08479841  1.17157876  0.5998191 ]
 [-0.51652143  1.90989153 -1.3673325  -1.01372936]
 [ 0.42633515 -0.52806284  0.60737626  0.86874385]
 [ 1.25133465  0.35846602  1.11515851  1.54105571]
 [-0.98794971  1.02336267 -1.3673325  -1.14819173]
 [-1.22366386 -0.08479841 -1.31091225 -1.14819173]
 [ 0.77990636 -0.52806284  0.49453576  0.46535673]
 [-0.39866435  2.57478818 -1.31091225 -1.28265411]
 [-1.22366386  0.80173045 -1.028811   -1.28265411]
 [-1.69509214 -0.30643063 -1.31091225 -1.28265411]
 [ 0.30847807 -0.08479841  0.66379651  0.86874385]
 [ 0.66204929  0.35846602  0.43